version: '3.4'
services:
  coworking-1:
    container_name: coworking-api-1
    build:
      context: ./
      dockerfile: DockerFile
    environment:
      - CONTAINER_ROLE=app
      - INSTALL_SCOUT=true
      - PM_MAX_CHILDREN=47
      - PM_START_SERVERS=11
      - PM_MIN_SPARE_SERVERS=11
      - PM_MAX_SPARE_SERVERS=32
      - PM_MAX_REQUEST=450
      - DB_HOST=coworking-db  # Actualiza esta línea
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    ports:
      - "3001:3001"
    volumes:
      - ./:/var/www
    networks:
      - coworking-network
  coworking-2:
    container_name: coworking-api-2
    build:
      context: ./
      dockerfile: DockerFile
    environment:
      - CONTAINER_ROLE=app
      - INSTALL_SCOUT=true
      - PM_MAX_CHILDREN=47
      - PM_START_SERVERS=11
      - PM_MIN_SPARE_SERVERS=11
      - PM_MAX_SPARE_SERVERS=32
      - PM_MAX_REQUEST=450
      - DB_HOST=coworking-db  # Actualiza esta línea
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    ports:
      - "3002:3002"
    volumes:
      - ./:/var/www
    networks:
      - coworking-network
  coworking-3:
    container_name: coworking-api-3
    build:
      context: ./
      dockerfile: DockerFile
    environment:
      - CONTAINER_ROLE=app
      - INSTALL_SCOUT=true
      - PM_MAX_CHILDREN=47
      - PM_START_SERVERS=11
      - PM_MIN_SPARE_SERVERS=11
      - PM_MAX_SPARE_SERVERS=32
      - PM_MAX_REQUEST=450
      - DB_HOST=coworking-db  # Actualiza esta línea
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    ports:
      - "3003:3003"
    volumes:
      - ./:/var/www
    networks:
      - coworking-network
  coworking-nginx:
    image: nginx:alpine
    container_name: coworking-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - coworking-network
  coworking-db:
    image: mysql:8.0.21
    container_name: coworking-db
    restart: always
    tty: true
    ports:
      - "33061:3306"
    environment:
      MYSQL_DATABASE: coworking_db
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql:delegated
    networks:
      - coworking-network
    command:
      - --default-authentication-plugin=mysql_native_password
      - --sort_buffer_size=1073741824
      - --max_connections=1000
networks:
  coworking-network:
    driver: bridge
volumes:
  dbdata:
    driver: local
