version: '3.4'
services:
  coworking:
    container_name: coworking-api
    build:
      context: ./
      dockerfile: dockerfile
    environment:
      - SERVER_PORT=3001
      - APPID=1111
    env_file:
      - .env
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - coworking-network
  
  coworking-2:
    container_name: coworking-api-2
    build:
      context: ./
      dockerfile: dockerfile
    environment:
      - SERVER_PORT=3002
      - APPID=2222
    env_file:
      - .env
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - coworking-network

  coworking-3:
    container_name: coworking-api-3
    build:
      context: ./
      dockerfile: dockerfile
    environment:
      - SERVER_PORT=3003
      - APPID=3333
    env_file:
      - .env
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - coworking-network
  
  coworking-nginx:
    image: nginx:alpine
    container_name: coworking-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8080:8080"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - coworking-network
  coworking-db:
    image: mysql:8.0.21
    container_name: coworking-db
    restart: always
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: coworking_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'  # needs to be enclosed with quotes
    volumes:
            - "./.data/db:/var/lib/mysql"
    networks:
      - coworking-network
    command:
      - --default-authentication-plugin=mysql_native_password
      - --sort_buffer_size=1073741824
      - --max_connections=1000
networks:
  coworking-network:
    driver: bridge

volumes:
  dbdata:
    driver: local